// examples/browser-action-mount-ui/entrypoints/content/App.tsx
import { useState } from "react";
import reactLogo from "@/assets/react.svg";
import wxtLogo from "@/public/wxt.svg";
import "./App.css";

function App() {
  const [count, setCount] = useState(0);

  return (
    <>
      <div>
        <a href="https://wxt.dev" target="_blank">
          <img src={wxtLogo} className="logo" alt="WXT logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>WXT + React</h1>
      <div className="card">
        <button onClick={() => setCount((count) => count + 1)}>
          count is {count}
        </button>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the WXT and React logos to learn more
      </p>
    </>
  );
}

export default App;

// examples/svelte-state-rune/src/entrypoints/popup/App.svelte
<script lang="ts">
  import svelteLogo from "../../assets/svelte.svg";
  import { counterState } from "@/lib/counter-state.svelte";
</script>

<main class="app">
  <div>
    <a href="https://wxt.dev" target="_blank" rel="noreferrer">
      <img src="/wxt.svg" class="logo" alt="WXT Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>
  <h1>WXT + Svelte</h1>

  <div class="card">
    <p>{counterState.state.counter}</p>
  </div>

  <p class="read-the-docs">Click on the WXT and Svelte logos to learn more</p>
</main>
